// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbXCI2cuS-chDpeGEbV6zvBRF1bSGAmt4',
    appId: '1:221220474869:web:276af5e91c67e2d2d35abc',
    messagingSenderId: '221220474869',
    projectId: 'carepulse-a3765',
    authDomain: 'carepulse-a3765.firebaseapp.com',
    storageBucket: 'carepulse-a3765.firebasestorage.app',
    measurementId: 'G-66FN6Y4Q4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg4u0geCv-ZGxJkQACCKGeLkKX42_HK5U',
    appId: '1:221220474869:android:2572bcc45ca43a43d35abc',
    messagingSenderId: '221220474869',
    projectId: 'carepulse-a3765',
    storageBucket: 'carepulse-a3765.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdksvJhzvs9AZrW3U_yH4CUFXS9MWe0E4',
    appId: '1:221220474869:ios:1a3084d15e54dd04d35abc',
    messagingSenderId: '221220474869',
    projectId: 'carepulse-a3765',
    storageBucket: 'carepulse-a3765.firebasestorage.app',
    iosBundleId: 'com.example.carepulseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdksvJhzvs9AZrW3U_yH4CUFXS9MWe0E4',
    appId: '1:221220474869:ios:1a3084d15e54dd04d35abc',
    messagingSenderId: '221220474869',
    projectId: 'carepulse-a3765',
    storageBucket: 'carepulse-a3765.firebasestorage.app',
    iosBundleId: 'com.example.carepulseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbXCI2cuS-chDpeGEbV6zvBRF1bSGAmt4',
    appId: '1:221220474869:web:169af2d976ae03a1d35abc',
    messagingSenderId: '221220474869',
    projectId: 'carepulse-a3765',
    authDomain: 'carepulse-a3765.firebaseapp.com',
    storageBucket: 'carepulse-a3765.firebasestorage.app',
    measurementId: 'G-F8638GSCWB',
  );
}
